
package br.ufrpe.dc.soa;

import javax.jws.WebParam.Mode;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding.Style;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-04-01T18:01:20.072-03:00
 * Generated source version: 3.5.1
 *
 */

@WebService
public interface Calculadora_PortType {

    public float sub(

        float arg0,
        float arg1
    );

    public float div(

        float arg0,
        float arg1
    );

    public float mult(

        float arg0,
        float arg1
    );

    public float somar(

        float arg0,
        float arg1
    );
}
