
package br.ufrpe.dc.soa.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.1
 * Fri Apr 01 18:01:19 BRT 2022
 * Generated source version: 3.5.1
 */

@XmlRootElement(name = "divResponse", namespace = "http://soa.dc.ufrpe.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "divResponse", namespace = "http://soa.dc.ufrpe.br/")

public class DivResponse {

    @XmlElement(name = "return")
    private float _return;

    public float getReturn() {
        return this._return;
    }

    public void setReturn(float new_return)  {
        this._return = new_return;
    }

}

